# Site settings
title: "BioVis 2023"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2023"
url: "http://biovis.net"
conferenceshort: "BioVis 2023"

#FIX ME: the event number is most likely not correct
#eventNum: "12th"

IEEE_conference_date: "October 22-27, 2023"
IEEE_conference_place: "Melbourne, Australia"

year: 2023

# Old deadlines so I remember what they're called
# When everything breaks
IEEE_deadline_submission: "August 17, 2023"
IEEE_deadline_notification: "August 24, 2023"
IEEE_deadline_camera: "August 31, 2023"
#IEEE_deadline_poster: "TBD"

ismb_conference_name: "ISMB/ECCB 2023"
ismb_conference_link: "https://www.iscb.org/ismbeccb2023"
ismb_conference_registration_link: "https://www.iscb.org/ismbeccb2023-register"
ismb_conference_date: "July 23 - 27, 2023"
ismb_conference_place: "Lyon, France (and virtual)"
ismb_conference_key_dates_link: "https://www.iscb.org/ismbeccb2023-dates"

ismb_cosi_date: "July 25, 2023"

ismb_paper_submission_deadline: "January 19, 2023"
ismb_paper_conditional_acceptance: "March 9, 2023"
ismb_paper_revision_deadline: "March 23, 2023"
ismb_paper_final_acceptance: "April 10, 2023"

ismb_talk_submission_deadline: "April 20, 2023"
ismb_talk_acceptance: "May 11, 2023"

ismb_poster_submission_deadline: "April 20, 2023"
ismb_poster_acceptance: "May 11, 2023"
ismb_poster_late_submission_deadline: "May 18, 2023"
ismb_poster_late_acceptance: "May 25, 2023"

ismb_paper_submission_link: "https://www.iscb.org/ismbeccb2023-submissions/proceedings"
ismb_abstract_submission_link: "https://www.iscb.org/ismbeccb2023-submissions/abstracts"

#bmc_submission_deadline: ""
#bmc_conditional_accept: ""
#bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
    - posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
lang: en-US
